// Thẻ Giới V0.3: 30 cards in six families. Pure card metadata; combat resolution is in core.mjs.
export const EXTRA_CARDS={
  venom:{name:"Độc Châm",cost:1,school:"Độc",kind:"magic",rarity:"common",icon:"poison",desc:"Gây 5 sát thương và 3 Độc."},
  toxinburst:{name:"Độc Bạo",cost:2,school:"Độc",kind:"magic",rarity:"uncommon",icon:"poison",desc:"Gây 8 sát thương + 4 mỗi tầng Độc, tiêu hao một nửa Độc (làm tròn lên)."},
  plague:{name:"Ôn Dịch",cost:2,school:"Độc",kind:"magic",rarity:"uncommon",icon:"poison",desc:"Đặt 5 Độc và 1 Thiêu Đốt."},
  serpent:{name:"Xà Ảnh",cost:2,school:"Độc",kind:"attack",rarity:"uncommon",icon:"poison",desc:"Gây 13 sát thương, đặt 2 Độc; nếu địch đã nhiễm Độc, đặt thêm 2."},
  antivenom:{name:"Luyện Dược",cost:1,school:"Độc",kind:"guard",rarity:"common",icon:"poison",desc:"Hồi 6 Máu, nhận Khiên bằng 2 lần số Độc trên địch (tối đa 16)."},
  quicken:{name:"Gia Tốc",cost:0,school:"Thời Không",kind:"magic",rarity:"common",icon:"clock",desc:"Rút thêm 1 lá ngay lập tức."},
  rewind:{name:"Hồi Tố",cost:1,school:"Thời Không",kind:"magic",rarity:"uncommon",icon:"clock",desc:"Đưa lá cuối cùng khác Hồi Tố từ chồng bài bỏ về tay."},
  chronostep:{name:"Thời Bộ",cost:1,school:"Thời Không",kind:"guard",rarity:"uncommon",icon:"clock",desc:"Nhận 9 Khiên và 1 năng lượng tức thời."},
  timecut:{name:"Không Trảm",cost:1,school:"Thời Không",kind:"attack",rarity:"uncommon",icon:"clock",desc:"Gây 7 sát thương + 4 mỗi loại Thiên Phú đang kích hoạt."},
  timeloop:{name:"Vọng Thời",cost:2,school:"Thời Không",kind:"magic",rarity:"rare",icon:"clock",desc:"Tái hiện dư âm chiêu tấn công/phép gần nhất: gây 12 sát thương và thêm trạng thái theo hệ."},
  wisp:{name:"Triệu Linh",cost:1,school:"Triệu Hồi",kind:"summon",rarity:"common",icon:"summon",desc:"Triệu hồi 1 Linh Hồn; mỗi cuối lượt tấn công 3 sát thương (tối đa 4)."},
  golem:{name:"Thạch Vệ",cost:2,school:"Triệu Hồi",kind:"summon",rarity:"uncommon",icon:"summon",desc:"Triệu hồi 1 Thạch Vệ; trước đòn địch nhận 4 Khiên mỗi Thạch Vệ (tối đa 3)."},
  swarm:{name:"Quần Linh",cost:2,school:"Triệu Hồi",kind:"summon",rarity:"rare",icon:"summon",desc:"Triệu hồi 2 Linh Hồn, không vượt quá giới hạn 4."},
  sacrifice:{name:"Hiến Linh",cost:1,school:"Triệu Hồi",kind:"magic",rarity:"uncommon",icon:"summon",desc:"Hiến tế 1 triệu hồi, gây 17 sát thương và hồi 7 Máu; nếu không có, nhận 5 Khiên."},
  spiritbond:{name:"Linh Khế",cost:1,school:"Triệu Hồi",kind:"magic",rarity:"uncommon",icon:"summon",desc:"Gây 4 sát thương + 5 mỗi triệu hồi, nhận 2 Khiên mỗi triệu hồi."},
  steam:{name:"Băng Hỏa Hơi",cost:1,school:"Hỗn Mang",kind:"magic",rarity:"uncommon",icon:"star",desc:"Gây 7 sát thương + 3 mỗi tầng Băng Giá và Thiêu Đốt; tiêu hao 1 tầng mỗi loại."},
  thunderfire:{name:"Lôi Hỏa",cost:2,school:"Hỗn Mang",kind:"magic",rarity:"rare",icon:"star",desc:"Gây 11 sát thương + 2 mỗi Lôi Ấn, đặt thêm 1 Lôi Ấn và 2 Thiêu Đốt."},
  crystalbolt:{name:"Băng Lôi Thương",cost:2,school:"Hỗn Mang",kind:"magic",rarity:"uncommon",icon:"star",desc:"Gây 9 sát thương + 3 mỗi Băng Giá, đặt thêm 2 Lôi Ấn."},
  bloodflame:{name:"Huyết Diễm",cost:2,school:"Hỗn Mang",kind:"attack",rarity:"uncommon",icon:"star",desc:"Gây 10 sát thương + 4 mỗi Xuất Huyết, thêm 2 Thiêu Đốt và hồi 4 Máu."},
  entropy:{name:"Hỗn Mang Trảm",cost:3,school:"Hỗn Mang",kind:"magic",rarity:"rare",icon:"star",desc:"Gây 10 sát thương + 3 mỗi tầng trạng thái (tối đa 20 tầng), tiêu hao 1 tầng mỗi loại."},
  stormheart:{name:"Lôi Tâm",cost:1,school:"Lôi",kind:"passive",rarity:"uncommon",icon:"bolt",desc:"Thiên Phú: mỗi lá Lôi đặt thêm 1 Lôi Ấn. Tồn tại trong trận, cộng dồn tối đa 2."},
  pyromancer:{name:"Hỏa Linh",cost:1,school:"Hỏa",kind:"passive",rarity:"uncommon",icon:"flame",desc:"Thiên Phú: mỗi lá Hỏa đặt thêm 1 Thiêu Đốt. Tồn tại trong trận, cộng dồn tối đa 2."},
  venomheart:{name:"Độc Mạch",cost:1,school:"Độc",kind:"passive",rarity:"uncommon",icon:"poison",desc:"Thiên Phú: mỗi lá tấn công đặt thêm 1 Độc. Tồn tại trong trận, cộng dồn tối đa 2."},
  swordmaster:{name:"Kiếm Tâm",cost:1,school:"Kiếm Đạo",kind:"passive",rarity:"rare",icon:"sword",desc:"Thiên Phú: mỗi lượt, lá Kiếm Đạo đầu tiên cho +1 Kiếm Ý. Cộng dồn tối đa 2."},
  spiritwell:{name:"Linh Tuyền",cost:1,school:"Triệu Hồi",kind:"passive",rarity:"rare",icon:"summon",desc:"Thiên Phú: trước đòn đánh của địch, nhận 2 Khiên mỗi triệu hồi. Cộng dồn tối đa 2."},
  mirrorward:{name:"Kính Hộ Mệnh",cost:1,school:"Phòng Ngự",kind:"reaction",rarity:"uncommon",icon:"shield",desc:"Phản Ứng: đòn tấn công kế của địch giảm một nửa sát thương và phản 7 sát thương."},
  thornmail:{name:"Giáp Gai",cost:1,school:"Phòng Ngự",kind:"reaction",rarity:"common",icon:"shield",desc:"Nhận ngay 3 Khiên. Phản Ứng: lần tấn công kế của địch chịu 12 sát thương phản đòn."},
  frostward:{name:"Băng Phản",cost:1,school:"Băng",kind:"reaction",rarity:"uncommon",icon:"snow",desc:"Phản Ứng: đòn tấn công kế của địch giảm 5 sát thương, đặt 2 Băng Giá."},
  bloodpact:{name:"Huyết Khế",cost:1,school:"Huyết",kind:"reaction",rarity:"uncommon",icon:"blood",desc:"Phản Ứng: sau đòn tấn công kế của địch, nếu sống sót, hồi 7 Máu và +1 Kiếm Ý."},
  counterstrike:{name:"Phản Thiên Kiếm",cost:2,school:"Kiếm Đạo",kind:"reaction",rarity:"rare",icon:"sword",desc:"Phản Ứng: lần địch tấn công kế tiếp, phản 16 sát thương và đặt 1 Lôi Ấn."}
};
